on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Generate token to access "common" repository
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          repositories: common
          app-id: ${{ secrets.ACCESS_COMMON_REPO_APP_ID }}
          private-key: ${{ secrets.ACCESS_COMMON_REPO_APP_PRIVATE_KEY }}

      - name: Clone "common" repository
        uses: actions/checkout@v5
        with:
          repository: OakFoil/common
          path: common
          token: ${{ steps.generate-token.outputs.token }}
      - run: mv common ../common

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Get packages
        run: flutter pub get

      - name: Generate autogenerated files
        run: flutter pub run build_runner build

      - name: Build app for Web
        run: flutter build web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https:\\sched-gen.ct.ws
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: build
          path: build

      - name: Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/web/
          server-dir: htdocs/

      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: build
